### ISSUE TITLE
X-UA-Compatible

### ISSUE THREAD

**Issue by mbrookes** [RailsApps/rails3-bootstrap-devise-cancan#10]
"As a Rails developer, you don’t have to add the X-UA-Compatible metatag to your application layout files or set an HTTP header in your ApplicationController."

http://railsapps.github.com/rails-html5-boilerplate.html

**Comment by DanielKehoe** [comment]
Thanks for pointing out the issue. I've updated the application layout to remove the unneeded X-UA-Compatible metatag.

**Comment by mbrookes** [comment]
No prob, sorry my submission was so terse, and thanks for considering it :-)

**Comment by DanielKehoe** [comment]
No problem, happy to see a terse issue when it is so clear and actionable. I ignored it because it was low priority (just cleaned things up and didn't cause failures) but I'm catching up now. It's rather amusing since I wrote the article that said it was not needed and never noticed that my example apps were still using it. Anyway, thanks for taking the time to bring it up.
