### ISSUE TITLE
_navigation checks are role-based not action based.

### ISSUE THREAD

**Issue by hadifarnoud** [RailsApps/rails3-bootstrap-devise-cancan#25]
why are you using `<% if current_user.has_role? :admin %>` and not `<% if can? :index, @user %>`

**Comment by DanielKehoe** [comment]
Either implementation will work. It's a matter of personal preference, I think, rather than best practice (though I am open to hearing why one is better than the other). To me, it seems more obvious to specify that the link is available to the admin user. The other way hides the rule in CanCan's ability model, which suits CanCan's philosophy of consolidating all access rules in one place. I'm not such a fan of the CanCan approach in this case, as I think it introduces obscurity. But maybe I'm wrong.

**Comment by hadifarnoud** [comment]
Ok. just checking.

I actually like CanCan for that. I encourage you to read http://lostechies.com/derickbailey/2011/05/24/dont-do-role-based-authorization-checks-do-activity-based-checks/
